/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_v1_users__user__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_v1_users__user__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_v1_users__user__patch"];
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_v1_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_v1_devices__device__get"];
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_v1_devices__device__delete"];
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_v1_devices__device__patch"];
        trace?: never;
    };
    "/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_v1_apps_get"];
        put?: never;
        /** Create App */
        post: operations["create_app_v1_apps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App */
        get: operations["get_app_v1_apps__app__get"];
        put?: never;
        post?: never;
        /** Delete App */
        delete: operations["delete_app_v1_apps__app__delete"];
        options?: never;
        head?: never;
        /** Update App */
        patch: operations["update_app_v1_apps__app__patch"];
        trace?: never;
    };
    "/v1/users/{user}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock User */
        post: operations["lock_user_v1_users__user__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock User */
        post: operations["unlock_user_v1_users__user__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plugin Types
         * @description List discovered plugin types from ``CURFEW_PLUGINS_DIRS``.
         *
         *     Reads from the registry built once at startup. Adding or removing a
         *     plugin folder requires a curfew-core restart (per ADR-013); this
         *     endpoint just reports what was discovered.
         */
        get: operations["list_plugin_types_v1_plugins_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_v1_plugins_get"];
        put?: never;
        /**
         * Create Assignment
         * @description Assign a plugin to a set of users.
         *
         *     Validates the type exists (404), the config matches the type's Pydantic
         *     schema (422), and the ``(type, instance_id)`` is unique (409). Builds
         *     the live instance *before* writing the DB row so a bad config / broken
         *     plugin returns 422 / 500 without leaving an orphan row behind.
         */
        post: operations["create_assignment_v1_plugins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/{type_name}/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Assignment */
        delete: operations["delete_assignment_v1_plugins__type_name___instance_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Assignment
         * @description Partial update.
         *
         *     If ``config`` changes, the runtime re-instantiates the plugin
         *     (PLAN.md option 1). ``users`` and ``enabled`` updates don't touch
         *     ``__init__``.
         */
        patch: operations["update_assignment_v1_plugins__type_name___instance_id__patch"];
        trace?: never;
    };
    "/v1/users/{user}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Status */
        get: operations["user_status_v1_users__user__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{device}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Status */
        get: operations["device_status_v1_devices__device__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_v1_settings_patch"];
        trace?: never;
    };
    "/v1/system/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_v1_system_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSnapshotRow */
        AgentSnapshotRow: {
            /** Device Id */
            device_id: number;
            /** Type */
            type: string;
            /** Last Heartbeat */
            last_heartbeat: string | null;
            /** Last Seen Version */
            last_seen_version: string | null;
        };
        /** AppCreate */
        AppCreate: {
            /** Slug */
            slug: string;
            /** Exe Paths */
            exe_paths?: string[];
            /** Process Names */
            process_names?: string[];
            /** Urls */
            urls?: string[];
        };
        /** AppRead */
        AppRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Exe Paths */
            exe_paths: string[];
            /** Process Names */
            process_names: string[];
            /** Urls */
            urls: string[];
        };
        /** AppUpdate */
        AppUpdate: {
            /** Slug */
            slug?: string | null;
            /** Exe Paths */
            exe_paths?: string[] | null;
            /** Process Names */
            process_names?: string[] | null;
            /** Urls */
            urls?: string[] | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Slug */
            slug: string;
            type: components["schemas"]["DeviceType"];
            os: components["schemas"]["DeviceOS"];
            /** Owner Id */
            owner_id?: number | null;
            /** Mac */
            mac?: string[];
            /**
             * Managed
             * @default true
             */
            managed: boolean;
        };
        /**
         * DeviceOS
         * @enum {string}
         */
        DeviceOS: "windows" | "macos" | "linux" | "ios" | "android";
        /** DeviceRead */
        DeviceRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            type: components["schemas"]["DeviceType"];
            os: components["schemas"]["DeviceOS"];
            /** Owner Id */
            owner_id: number | null;
            /** Mac */
            mac: string[];
            /** Managed */
            managed: boolean;
        };
        /**
         * DeviceType
         * @description Device form-factor.
         *
         *     LAPTOP folds into PC: enforcement (NTFS ACL, registry policy, process kill)
         *     is identical for laptops and desktops. If a future feature needs to
         *     distinguish them, it can add the column then.
         * @enum {string}
         */
        DeviceType: "pc" | "phone" | "tablet" | "console" | "tv";
        /**
         * DeviceUpdate
         * @description All fields optional. Send ``owner_id: null`` to clear the owner.
         */
        DeviceUpdate: {
            /** Slug */
            slug?: string | null;
            type?: components["schemas"]["DeviceType"] | null;
            os?: components["schemas"]["DeviceOS"] | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Mac */
            mac?: string[] | null;
            /** Managed */
            managed?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Db */
            db: string;
        };
        /**
         * LockStatus
         * @description ``{locked, reasons}`` — the user/device-scope rule pipeline output.
         */
        LockStatus: {
            /** Locked */
            locked: boolean;
            /** Reasons */
            reasons?: components["schemas"]["Reason"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ManifestSnapshotRow */
        ManifestSnapshotRow: {
            /** Type */
            type: string;
            /** Version */
            version: string;
            /** Sha256 */
            sha256: string;
            /** Url */
            url: string;
        };
        /**
         * MeResponse
         * @description Identity payload for the current actor — drives frontend nav state.
         */
        MeResponse: {
            /** Kind */
            kind: string;
            /** Username */
            username: string | null;
            role: components["schemas"]["UserRole"];
        };
        /**
         * PluginAssignmentCreate
         * @description ``POST /v1/plugins`` body. ``instance_id`` defaults to ``"default"``.
         */
        PluginAssignmentCreate: {
            /** Type */
            type: string;
            /**
             * Instance Id
             * @default default
             */
            instance_id: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Users */
            users?: string[];
        };
        /**
         * PluginAssignmentRead
         * @description One assigned plugin instance — what ``GET /v1/plugins`` returns.
         *
         *     Mirrors the ``plugin_assignments`` row + the in-memory enabled flag.
         *     Doesn't surface the live ``Plugin`` instance object; that's a runtime
         *     concern, not part of the API contract.
         */
        PluginAssignmentRead: {
            /** Type */
            type: string;
            /** Instance Id */
            instance_id: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Users */
            users: string[];
            /** Enabled */
            enabled: boolean;
        };
        /**
         * PluginAssignmentUpdate
         * @description ``PATCH /v1/plugins/{type}/{instance_id}`` body. All-optional.
         */
        PluginAssignmentUpdate: {
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Users */
            users?: string[] | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** PluginSnapshotRow */
        PluginSnapshotRow: {
            /** Type */
            type: string;
            /** Instance Id */
            instance_id: string;
            /** Users */
            users: string[];
            /** Enabled */
            enabled: boolean;
        };
        /**
         * PluginTypeRead
         * @description One discovered plugin type as returned by ``GET /v1/plugins/types``.
         *
         *     Reflects what the loader found at startup. ``error`` is non-null when
         *     the plugin folder failed to load (missing manifest, no Plugin subclass,
         *     bad imports, etc.); successfully-loaded plugins have ``error: null``
         *     and the manifest fields populated.
         */
        PluginTypeRead: {
            /** Type */
            type: string;
            /** Name */
            name?: string | null;
            /** Version */
            version?: string | null;
            /** Description */
            description?: string | null;
            /** Config Schema */
            config_schema?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Has Requirements Txt
             * @default false
             */
            has_requirements_txt: boolean;
        };
        /**
         * Reason
         * @description A single rule's contribution to the lock status.
         *
         *     Has a required ``kind`` discriminator (e.g. ``"manual_lock"``,
         *     ``"out_of_schedule"``, ``"budget_exhausted"``); rule-specific detail fields
         *     are allowed and pass through (``extra="allow"``). Clients render ``kind``
         *     and ignore unknown extras.
         */
        Reason: {
            /** Kind */
            kind: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SettingsRead
         * @description The runtime-mutable kernel tunables (singleton row).
         */
        SettingsRead: {
            /** Agent Tick Seconds */
            agent_tick_seconds: number;
            /** Manifest Tick Seconds */
            manifest_tick_seconds: number;
            /** Plugin Resync Seconds */
            plugin_resync_seconds: number;
            /** Plugin Reconcile Timeout Seconds */
            plugin_reconcile_timeout_seconds: number;
            /** Audit Retention Days */
            audit_retention_days: number;
        };
        /**
         * SettingsUpdate
         * @description Partial update; ``Field(gt=0)`` rejects zero/negative tick values at the boundary.
         */
        SettingsUpdate: {
            /** Agent Tick Seconds */
            agent_tick_seconds?: number | null;
            /** Manifest Tick Seconds */
            manifest_tick_seconds?: number | null;
            /** Plugin Resync Seconds */
            plugin_resync_seconds?: number | null;
            /** Plugin Reconcile Timeout Seconds */
            plugin_reconcile_timeout_seconds?: number | null;
            /** Audit Retention Days */
            audit_retention_days?: number | null;
        };
        /**
         * SystemSnapshot
         * @description Aggregate dump of live system state for diagnostics / backup.
         *
         *     ``audit_log`` and ``agent_tokens`` deliberately stay out of the dump:
         *     audit_log is unbounded; agent_tokens stores secret hashes. The ``counts``
         *     block surfaces the row counts so operators still know they exist.
         */
        SystemSnapshot: {
            /** Users */
            users: components["schemas"]["UserRead"][];
            /** Devices */
            devices: components["schemas"]["DeviceRead"][];
            /** Apps */
            apps: components["schemas"]["AppRead"][];
            /** Agents */
            agents: components["schemas"]["AgentSnapshotRow"][];
            /** Plugins */
            plugins: components["schemas"]["PluginSnapshotRow"][];
            /** User Locks */
            user_locks: components["schemas"]["UserLockSnapshotRow"][];
            /** Manifests */
            manifests: components["schemas"]["ManifestSnapshotRow"][];
            settings: components["schemas"]["SettingsRead"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** @default member */
            role: components["schemas"]["UserRole"];
            /**
             * Managed
             * @default true
             */
            managed: boolean;
        };
        /** UserLockSnapshotRow */
        UserLockSnapshotRow: {
            /** User Id */
            user_id: number;
            /** Manual Lock */
            manual_lock: boolean;
            /**
             * Set At
             * Format: date-time
             */
            set_at: string;
            /** Set By */
            set_by: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            role: components["schemas"]["UserRole"];
            /** Managed */
            managed: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "member" | "manager" | "admin";
        /**
         * UserUpdate
         * @description All fields optional; only fields actually sent are applied.
         */
        UserUpdate: {
            /** Username */
            username?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Managed */
            managed?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    change_password_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    create_user_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_v1_users__user__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_v1_users__user__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_v1_users__user__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"][];
                };
            };
        };
    };
    create_device_v1_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_v1_devices__device__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_v1_devices__device__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_v1_devices__device__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_apps_v1_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRead"][];
                };
            };
        };
    };
    create_app_v1_apps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_v1_apps__app__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_app_v1_apps__app__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_app_v1_apps__app__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_user_v1_users__user__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_user_v1_users__user__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plugin_types_v1_plugins_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginTypeRead"][];
                };
            };
        };
    };
    list_assignments_v1_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginAssignmentRead"][];
                };
            };
        };
    };
    create_assignment_v1_plugins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginAssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginAssignmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assignment_v1_plugins__type_name___instance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assignment_v1_plugins__type_name___instance_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginAssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginAssignmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_status_v1_users__user__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_status_v1_devices__device__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_settings_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_v1_system_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSnapshot"];
                };
            };
        };
    };
}
