"""curfew shared library.

The ``Settings`` name is intentionally NOT re-exported at this top level — it
collides between two valid concepts: the boot-time ``Settings`` BaseSettings in
``curfew.config`` and the runtime ``Settings`` SQLModel row in ``curfew.models``.
Always import explicitly from one of those modules.
"""

from curfew.audit import record_audit
from curfew.auth import Actor, root_actor
from curfew.db import get_engine, get_session, make_engine, reset_engine_cache
from curfew.models import (
    Agent,
    AgentToken,
    App,
    AuditLog,
    AuditTargetKind,
    Device,
    DeviceOS,
    DeviceType,
    Manifest,
    PluginAssignment,
    User,
    UserLock,
    UserRole,
    UserSession,
)
from curfew.passwords import hash_password, verify_password
from curfew.plugin import Plugin, PluginManifest, ReconcileResult, ReconcileStatus, Scope
from curfew.plugin_loader import PluginRegistry, PluginType, discover_plugins
from curfew.plugin_runtime import (
    AlreadyAssignedError,
    AssignedInstance,
    NotAssignedError,
    PluginInstantiationError,
    PluginRuntime,
    UnknownPluginTypeError,
)
from curfew.rules import (
    RulePipeline,
    device_scope,
    manual_lock_rule,
    register_kernel_rules,
    user_scope,
)
from curfew.schemas import (
    AgentSnapshotRow,
    AppCreate,
    AppRead,
    AppUpdate,
    ChangePasswordRequest,
    DeviceCreate,
    DeviceRead,
    DeviceUpdate,
    LockStatus,
    LoginRequest,
    ManifestSnapshotRow,
    MeResponse,
    PluginAssignmentCreate,
    PluginAssignmentRead,
    PluginAssignmentUpdate,
    PluginSnapshotRow,
    PluginTypeRead,
    Reason,
    SettingsRead,
    SettingsUpdate,
    SystemSnapshot,
    UserCreate,
    UserLockSnapshotRow,
    UserRead,
    UserUpdate,
)

__all__ = [
    "Actor",
    "Agent",
    "AgentSnapshotRow",
    "AgentToken",
    "AlreadyAssignedError",
    "App",
    "AppCreate",
    "AppRead",
    "AppUpdate",
    "AssignedInstance",
    "AuditLog",
    "AuditTargetKind",
    "ChangePasswordRequest",
    "Device",
    "DeviceCreate",
    "DeviceOS",
    "DeviceRead",
    "DeviceType",
    "DeviceUpdate",
    "LockStatus",
    "LoginRequest",
    "Manifest",
    "ManifestSnapshotRow",
    "MeResponse",
    "NotAssignedError",
    "Plugin",
    "PluginAssignment",
    "PluginAssignmentCreate",
    "PluginAssignmentRead",
    "PluginAssignmentUpdate",
    "PluginInstantiationError",
    "PluginManifest",
    "PluginRegistry",
    "PluginRuntime",
    "PluginSnapshotRow",
    "PluginType",
    "PluginTypeRead",
    "Reason",
    "ReconcileResult",
    "ReconcileStatus",
    "RulePipeline",
    "Scope",
    "SettingsRead",
    "SettingsUpdate",
    "SystemSnapshot",
    "UnknownPluginTypeError",
    "User",
    "UserCreate",
    "UserLock",
    "UserLockSnapshotRow",
    "UserRead",
    "UserRole",
    "UserSession",
    "UserUpdate",
    "device_scope",
    "discover_plugins",
    "get_engine",
    "get_session",
    "hash_password",
    "make_engine",
    "manual_lock_rule",
    "record_audit",
    "register_kernel_rules",
    "reset_engine_cache",
    "root_actor",
    "user_scope",
    "verify_password",
]
